# This secret is used to set the initial credentials of the node container.
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "midserver.fullname" . }}-secret
  labels:
    {{- include "midserver.labels" . | nindent 4 }}
type: opaque
data:
  MID_INSTANCE_USERNAME: {{ default "" .Values.midEnv.MID_INSTANCE_USERNAME | b64enc | quote  }}
  MID_INSTANCE_PASSWORD: {{ default "" .Values.midEnv.MID_INSTANCE_PASSWORD | b64enc | quote }}
  MID_INSTANCE_URL: {{ default ""  .Values.midEnv.MID_INSTANCE_URL | b64enc | quote }}